Create data model
kiboma2021/Blog-app pull request #1
Opened 2022-10-17 21:12 UTC by kiboma2021

- Create a new app. Give it a meaningful name.
- Initialize your project with Git.
- Make sure that your project has Postgres database set up.
- Build your project schema.

- [ ] Create and run the necessary migration files.
- [ ] Table and column names should match the ERD diagram.
- [ ] Foreign keys should be included.
- [ ] All columns that are foreign keys should have a corresponding index.

![image](https://user-images.githubusercontent.com/93031593/196284404-2590586e-c9d9-4b01-b5db-a093a1feed38.png)

2022-10-17 21:58 UTC, VICTOR-CHUKWU requested changes
Hi @kiboma2021  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-17 21:58 UTC, VICTOR-CHUKWU commented on db/migrate/20221017202611_add_user_ref_to_comments.rb
> +    add_reference :comments, :user, null: false, foreign_key: true, index: true
- [ ] According to the project requirement kindly change the reference to user to author i.e `  t.references :author, foreign_key: { to_table: 'users' }`

2022-10-17 21:58 UTC, VICTOR-CHUKWU commented on db/migrate/20221017202912_add_user_ref_to_likes.rb
> +    add_reference :likes, :user, null: false, foreign_key: true, index: true
- [ ] According to the project requirement kindly change the reference to user to author i.e `t.references :author, foreign_key: { to_table: 'users' }`

2022-10-18 16:30 UTC, kiboma2021 commented on db/migrate/20221017202912_add_user_ref_to_likes.rb
> +    add_reference :likes, :user, null: false, foreign_key: true, index: true
@VICTOR-CHUKWU , This is done

2022-10-18 16:33 UTC, ShadyShawkat approved these changes
## Hi @kiboma2021, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-18 17:06 UTC, merged